auths/urls.py
from django.urls import re_path
from . import views

app_name = 'authentication'

# make a urls

urlpatterns = [
    re_path(r'^login$',views.login_index,name='login_index'),
    re_path(r'^signup$',views.signup_index,name='signup_index'),
    re_path(r'^process_login',views.login_process,name='login_process'),
    re_path(r'^process_signup',views.signup_process,name='signup_process'),
    re_path(r'logout',views.logout,name='logout'),
]

homepage/urls.py
from django.urls import re_path
from . import views

app_name = 'homepage'

# make a urls

urlpatterns = [
    re_path(r'^$',views.index,name='index'),
]

praktikum/urls.py
from django.conf.urls import include
from django.urls import re_path
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^',include('homepage.urls',namespace='homepage')),
    re_path(r'^auths/',include('auths.urls',namespace='authentication')),
    re_path(r'^detail/',include('mobil.urls',namespace='detail')),
    re_path(r'^pesan/',include('pesan.urls',namespace='pesan')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/base_logged.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Beranda</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/Navigation-with-Button.css' %}">
    <link rel="stylesheet" href="{% static 'css/homepage_logged.css' %}">
    {% block more_styles %}{% endblock more_styles %}
</head>

<body>
    <div>
        <nav class="navbar navbar-light navbar-expand-md navigation-clean-button">
            <div class="container"><a class="navbar-brand linkUtama" href="{% url 'homepage:index' %}" style="background: url('{% static 'img/logo-ham.jpg' %}');"></a>

                <ul class="nav navbar-nav mr-auto">
                    <li class="nav-item" role="presentation"><a class="nav-link {{is_sedan}}" href="/detail/sedan">Sedan</a></li>
                    <li class="nav-item" role="presentation"><a class="nav-link {{is_mpv}}" href="/detail/mpv">MPV</a></li>
                    <li class="nav-item" role="presentation"><a class="nav-link {{is_suv}}" href="/detail/suv">SUV</a></li>
                    <li class="nav-item" role="presentation"><a class="nav-link {{is_hatchback}}" href="/detail/hatchback">Hatchback</a></li>
                </ul>
                <div class="collapse navbar-collapse" id="navcol-1"><span class="navbar-text actions" style="margin-left: auto;"> <a class="login" href="#">Halo,{{nama_lengkap}}</a><a class="btn btn-light action-button" role="button" href="{% url 'authentication:logout' %}">Logout</a></span></div>
            </div>
        </nav>
    </div>
    {% block content %}{% endblock content %}
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/daftar.js' %}"></script>
    {% block more_js %}{% endblock more_js %}
</body>

</html>

templates/description_lab2addon.html
{% extends "base.html" %}
{% block content %}
<h3 style="text-align: center">Hi all, This is my complete biodata</h3>
<table align="center" style="text-align: center">
    {% for bio in bio_dict %}
        <tr>
            <td class="subject">{{ bio.subject }}</td>
            <td class="value">{{ bio.value }}</td>
        </tr>
    {% endfor %}
</table>
<br><br>
{% endblock %}

templates/to_do_list.html
{% extends "base.html" %}
{% block content %}
<h3 style="text-align: center">Hai semua, berikut adalah Catatan Harianku</h3>
<br><br>
<div class="row">
    <div class="col-md-6 col-xs-6">
        <table align="center" style="text-align: center">
            <tr>
                <th>Tanggal</th>
                <th>Yang akan dikerjakan</th>
            </tr>
            {% for diary_data in diary_dict %}
                <tr>
                    <td class="date">{{ diary_data.date }}</td>
                    <td class="activity">{{ diary_data.activity }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
    <div class="col-md-6 col-xs-6">
        <form method="POST" action="add_activity/">
            {% csrf_token %}
            <table>
                <tr>
                    <td>
                        Tanggal
                    </td>
                    <td>
                        <input type="datetime-local" name="date" id="date" required="required"/>
                    </td>
                </tr>
                <tr>
                    <td>
                        Kegiatan
                    </td>
                    <td>
                        <input type="text" name="activity" id="activity" size="25"/>
                    </td>
                </tr>
            </table>
            <button type="submit" class="button btn-success">Submit</button>
        </form>
    </div>
</div>
{% endblock %}