auths/urls.py
from django.urls import re_path
from . import views

app_name = 'authentication'

# make a urls

urlpatterns = [
    re_path(r'^login$',views.login_index,name='login_index'),
    re_path(r'^signup$',views.signup_index,name='signup_index'),
    re_path(r'^process_login',views.login_process,name='login_process'),
    re_path(r'^process_signup',views.signup_process,name='signup_process'),
    re_path(r'logout',views.logout,name='logout'),
]

pesan/urls.py
from django.urls import re_path
from . import views

app_name = 'pesan'

# mulai cok

urlpatterns = [
    re_path(r'^(?P<nama>[\w]+)$',views.index),
    re_path(r'^proses/$',views.proses,name='proses')
]

praktikum/urls.py
from django.conf.urls import include
from django.urls import re_path
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^',include('homepage.urls',namespace='homepage')),
    re_path(r'^auths/',include('auths.urls',namespace='authentication')),
    re_path(r'^detail/',include('mobil.urls',namespace='detail')),
    re_path(r'^pesan/',include('pesan.urls',namespace='pesan')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

pesan/models.py
from django.db import models

# Create your models here.

class pemesan(models.Model):
    nama = models.CharField(max_length=30,default='Tidak Diketahui')
    alamat = models.CharField(max_length=200,default='Tidak Diketahui')
    no_telp = models.CharField(max_length=15,default='Tidak Diketahui')
    email = models.EmailField(max_length=100,default='tidak diketahui')
    kota = models.CharField(max_length=20,default='Tidak Diketahui')
    provinsi = models.CharField(max_length=20,default='Tidak Diketahui')
    tanggal_beli = models.DateTimeField(auto_now_add=True)
    mobil = models.ForeignKey("mobil.data_mobil",on_delete=models.CASCADE)

    def __str__(self):
        return str(self.nama) +' , '+ str(self.mobil) 
    

pesan/forms.py
from django import forms

# your forms go here

def createForm(tipe='text',placeholder='',style=''):
    p = dict()
    p['type'] = tipe
    p['placeholder'] = placeholder
    p['style'] = style
    return p

class userBuyForm(forms.Form):
    attribute_nama_lengkap = createForm(placeholder='Nama Lengkap')
    attribute_alamat_lengkap = createForm(placeholder='Alamat Lengkap',style='border-radius: 7px;outline: none;border-style: groove;background: transparent;width: 600px;height: 100px;color: #000;margin-top: 20px;margin-left: 50px;')
    attribute_no_telp = createForm(tipe='tel',placeholder='Nomor Hp')
    attribute_email = createForm(tipe='email',placeholder='Email Anda')
    attribute_kota = createForm(placeholder='Kota')
    attribute_provinsi = createForm(placeholder='Provinsi')

    nama_lengkap = forms.CharField(required=True,widget=forms.TextInput(attribute_nama_lengkap))
    alamat_lengkap = forms.CharField(required=True,widget=forms.TextInput(attribute_alamat_lengkap))
    no_telp = forms.CharField(required=True,widget=forms.TextInput(attribute_no_telp))
    email = forms.EmailField(required=True,widget=forms.EmailInput(attribute_email))
    kota = forms.CharField(required=True,widget=forms.TextInput(attribute_kota))
    provinsi = forms.CharField(required=True,widget=forms.TextInput(attribute_provinsi))

pesan/views.py
from django.shortcuts import render
from django.apps import apps
from .forms import userBuyForm
from django.http import Http404
from .models import pemesan

# Create your views here.

def dapatkan_data(request='',data=''):
    return request.POST[data]

data_pengguna = apps.get_model('auths','data_pengguna')
daftar_mobil = apps.get_model('mobil','data_mobil')

def index(request,nama):
    if nama =='corolla' or nama == 'kijang':
        if nama == 'corolla' :
            nama = 'corolla altis'
            pass
        else:
            nama = 'kijang innova'
            pass
    elif daftar_mobil.objects.filter(nama_mobil=nama).count() == 0:
        raise Http404('Nama Mobil Tidak Ditemukan')
    request.session['nama_mobil'] = nama
    response = {
        'form' : userBuyForm,
    }
    return render(request,'pesan.html',response)

def proses(request):
    if request.method == 'POST':
        nama = dapatkan_data(request,data='nama_lengkap')
        alamat = dapatkan_data(request,data='alamat_lengkap')
        hp = dapatkan_data(request,data='no_telp')
        email = dapatkan_data(request,data='email')
        kota = dapatkan_data(request,data='kota')
        provinsi = dapatkan_data(request,data='provinsi')
        print(request.session['nama_mobil'])
        masukkan = pemesan(nama=nama,alamat=alamat,no_telp=hp,email=email,kota=kota,provinsi=provinsi,mobil=daftar_mobil.objects.get(nama_mobil=request.session['nama_mobil']))
        masukkan.save()

        response = {
            'nama_lengkap' : data_pengguna.objects.get(email=request.session['active_email']).nama_lengkap
        }
        return render(request,'dealer.html',response)
    else:
        raise Http404('Situs yang anda cari tidak ditemukan')    

pesan/templates/dealer.html
{% extends "base_logged.html" %}
{% load static from staticfiles %}
{% block content %}

<div style="position: fixed;height: 270px;top: 50PX;background: url({% static 'img/q.jpg' %});background-size: 100%;position: relative;background-repeat: no-repeat;"></div>
   <div style="margin-top: 50px;height: 100px;">
       <h4 style="margin-top: 100px;text-align: center;font-family: sans-serif;font-variant: initial;font-size: 40px;"><strong>Data anda sudah terekam</strong></h4>
       <h1 style="text-align: center;font-family: sans-serif;font-variant: initial;font-size: 20px;">Silakan kunjungi Dealer terdekat</h1>
   </div>
</div>
{% endblock content %}

pesan/templates/pesan.html
<!DOCTYPE html>
{% extends "base_logged.html" %}
{% load static from staticfiles %}
{% block content %}

    <div style="position: fixed;height: 270px;top: 50PX;background: url({% static 'img/w.jpg' %});background-size: 100%;position: relative;background-repeat: no-repeat;"></div>
    <div style="margin-top: 50px;height: 200px;">
        <h1 style="margin-top: 100px;margin-left: 50px;font-family: sans-serif;font-variant: initial;"><strong>Terimakasih atas Ketertarikan Anda</strong><br></h1>
        <h4 style="margin-left: 50px;font-size: 20px;"><br>Untuk melakukan <strong>KONSULTASI PEMBELIAN</strong> atau <strong>TEST DRIVE</strong><br><br>silakan isi Form dibawah ini, kunjungi dealer&nbsp;<strong>TOYOTA</strong> terdekat<br><br></h4>
    </div>
        <form action="{% url 'pesan:proses' %}" method="post" style="height: 850px;">
            <h3 style="margin-left: 50px;font-family: sans-serif;font-variant: initial;">
                <strong>Informasi data pribadi</strong>
                <br>
            </h3>
            {{form.nama_lengkap}}
            {{form.alamat_lengkap}}
            {{form.no_telp}}
            {{form.email}}
            {{form.kota}}
            {{form.provinsi}}
            {% csrf_token %}
            <br>
            <button class="btn-primary" type="submit" style="width: 100px;margin-left: 50px;margin-top: 20px;color: rgb(255,255,255);">Kirim</button>
        </form>
{% endblock content %}